#!/usr/bin/env bash

#
# Setup GTK Theme
#
THEME='MonoThemeDark'
THEME_SHADE='prefer-dark'
ICONS='kora'
FONT='Noto Sans 9'
CURSOR='Qogirr'

COMMAND='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${COMMAND} gtk-theme "$THEME"
	${COMMAND} color-scheme "$THEME_SHADE"
	${COMMAND} icon-theme "$ICONS"
	${COMMAND} cursor-theme "$CURSOR"
	${COMMAND} font-name "$FONT"
}

apply_themes