#
# Colors
#
foreground         #C1C1C1
background         #1A1A1A

# Tabs
active_tab_foreground     #FAFAFA
active_tab_background     #3a3a3a
inactive_tab_foreground   #727272
inactive_tab_background   #1A1A1A

# Border
active_border_color   #b392f0
inactive_border_color #1A1A1A
bell_border_color     #79b8ff

# Cursor
cursor #C1C1C1
cursor_text_color #727272

# Black
color0 #727272
color8 #585858

# Red
color1 #FF7A84
color9 #bf5c63

# Green
color2  #73daca
color10 #56a498

# Yellow
color3  #FF9800
color11 #bf7200

# Magenta
color4  #b392f0
color12 #866eb4

# Blue
color5  #79b8ff
color13 #5b8abf

# Cyan
color6  #7dcfff
color14 #4e819f

# White
color7  #C1C1C1
color15 #919191
